### ISSUE TITLE
Block news feed on page load

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/Twitter-Focus#4]
## Overview
Users should have their news feed hidden when they enter Twitter with the TwitterFocus extension

## Implementation Notes

Because the DOM content may not have loaded by the time the content script tries to hide it, we try hiding the news feed at an interval. 

This is how LinkedInFocus handles it: 

```
function blockNewsFeed () {
    function tryBlockingNewsFeed () {
        if (!hasNewsLoaded()) {
            return
        }
        setNewsVisibility(false)
        if (isNewsBlocked()) {
            clearInterval(intervalTimerId)
            displayQuote()
            return;
        }
    }
    if (!isNewsBlocked()) {
        intervalTimerId = setInterval(tryBlockingNewsFeed, 1000)
    }
}
```

More about setInterval [here](https://www.w3schools.com/jsref/met_win_setinterval.asp)

**Comment by daveavi** [comment]
I am wondering for this code why do we check if the news is blocked if we know that news has been loaded? Once we set the visibility to false, it should block anyway, right?

**Comment by daveavi** [comment]
I got to it to work now, I made the code a little bit faster, I felt that instead of letting the set of calls in the interval do the blocking if the HTML has already been loaded, just set the visibility to false right away
